SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
CREATE TABLE SYMBOL(
    SYMBOL_NAME VARCHAR(256),
    PRIMARY KEY (SYMBOL_NAME)
);

CREATE TABLE ACCOUNT(
    ACCOUNT_ID BIGINT,
    BALANCE DOUBLE PRECISION DEFAULT 0 CHECK (BALANCE >= 0),
    PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE POSITION(
    SYMBOL_NAME VARCHAR(256),
    ACCOUNT_ID BIGINT,
    AMOUNT DOUBLE PRECISION DEFAULT 0 CHECK (AMOUNT >= 0),
    PRIMARY KEY (SYMBOL_NAME, ACCOUNT_ID),
    FOREIGN KEY (SYMBOL_NAME) REFERENCES SYMBOL (SYMBOL_NAME) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE DEAL(
    DEAL_ID BIGSERIAL,
    ORDER_ID BIGINT,
    STATUS VARCHAR(256) DEFAULT 'EXECUTED',
    SYMBOL_NAME VARCHAR(256),
    AMOUNT DOUBLE PRECISION,
    EXECUTE_PRICE DOUBLE PRECISION DEFAULT 0,
    UPDATE_TIME BIGINT DEFAULT 0,
    PRIMARY KEY (DEAL_ID),
    FOREIGN KEY (SYMBOL_NAME) REFERENCES SYMBOL (SYMBOL_NAME) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE TRANSACTION(
    ORDER_ID BIGSERIAL,
    STATUS VARCHAR(256) DEFAULT 'OPEN',
    SYMBOL_NAME VARCHAR(256),
    ACCOUNT_ID BIGINT,
    AMOUNT DOUBLE PRECISION,
    LIMIT_PRICE DOUBLE PRECISION DEFAULT 0,
    UPDATE_TIME BIGINT DEFAULT 0,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (SYMBOL_NAME) REFERENCES SYMBOL (SYMBOL_NAME) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID) ON DELETE SET NULL ON UPDATE CASCADE
);
